### ISSUE TITLE
Using FastAPI or RESTFUL api

### ISSUE THREAD

**Issue by angelotheman** [angelotheman/RenTopia#3]
## FastAPI
Well, I kinda find FastAPI to be a bit simpler and more straightforward as compared to the other frameworks.

@ikuffourosei ,  you can actually bring your thoughts so that we note what can best help us. For now I'm building those sides of the architecture which are not framework specific, such as the models and some sql queries.

What do you think?

**Comment by angelotheman** [comment]
Oh and less I forget, FASTapi still adheres to the RESTApi architecture anyways, so I think it's still a good bet.

Yet still let me know your thoughts

**Comment by ikuffourosei** [comment]
FastAPI is a framework just like flask or Django rest. This is a simpler project. Using Flask will be better. using automatic authentication from FastAPI will not be a good PBL curve. I prefer using Flask.

**Comment by ikuffourosei** [comment]
I've been working all week that's why I am not active
Just closed from work

**Comment by angelotheman** [comment]
> I've been working all week that's why I am not active Just closed from work

Hmmm, I see. I had to do this like yesterday

**Comment by ikuffourosei** [comment]
i’m adding some methods to the models

**Comment by angelotheman** [comment]
> FastAPI is a framework just like flask or Django rest. This is a simpler project. Using Flask will be better. using automatic authentication from FastAPI will not be a good PBL curve. I prefer using Flask.

The authentication FastAPI offers can be a bit daunting yeah, but then in overall development, it is a bit faster.
For authentication I would probably use `OAuth2 Providers`

**Comment by ikuffourosei** [comment]
Come to discord

**Comment by angelotheman** [comment]
Alright, then we dicuss the frontend.

Great to have you back charlie

**Comment by ikuffourosei** [comment]
Just created a database class and I just saw that you have created it in
another directory

**Comment by ikuffourosei** [comment]
why are you using postgresql

**Comment by ikuffourosei** [comment]
Are you doing the project based on what tech you want to use or are you
building as a way of PBL on what you have learnt so far
?
